### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by kulak** [kataras/i18n#4]
It would be nice to upgrade dependencies of the project, because I think it is starting to pull some old versions of other packages.

Example of upgraded code is in my fork commit: https://github.com/kataras/i18n/commit/080c2395f8b1c88a97f9976d00b5e7d44c322e7b

**Comment by kataras** [comment]
Hello @kulak. I'll add dependabot so it can be done automatically :) Thanks!

**Comment by kulak** [comment]
Thank you
